### ISSUE TITLE
Decouple and upgrade dependencies to latest version

### ISSUE THREAD

**Issue by Incede** [LiskHQ/lisk-contracts#214]
### Description

- Upgrade [evm-connector](https://www.npmjs.com/package/@redstone-finance/evm-connector) to 0.6.2
- Decouple `redstone-protocol` and upgrade to use latest version of [@redstone-finance/protocol](https://www.npmjs.com/package/@redstone-finance/protocol) instead

### Acceptance Criteria

The dependent logic should be adjusted and tested for correct functionality

**Comment by sameersubudhi** [comment]
https://github.com/redstone-finance/redstone-evm-examples could be used for reference to update the evm-connector  dependency.

**Comment by matjazv** [comment]
Fixed by #220.
